import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Character, GetCharacterResults } from "../types";
import imageLoader from "../imageLoader";






const Home: NextPage<{ characters: Character[] }> = ({ characters }) => {
  return (

    <div>
      <main>

        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </main>



      <div>
        {characters.map(character => (
          <div key={character.id}>
            <Link href={`/character/${character.id}`}>
              <h3>{character.name}</h3>
            </Link>
            <Image src={character.image} alt={character.name} width="200" height="200" />

          </div>
        ))}
      </div>

      <footer className="flex h-24 w-full items-center justify-center border-t">
        <a
          className="flex items-center justify-center gap-2"
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <Image loader={imageLoader} unoptimized src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </a>
      </footer>
    </div>


  )
}


export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://rickandmortyapi.com/api/character");
  const { results }: GetCharacterResults = await res.json();

  return {
    props: {
      characters: results,
    },
  };
};

export default Home
